/*
 * Created on 2018-01-15 ( Time 10:47:01 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
<template>
    <div class="container">
    <div class="container">
        <form class="form-horizontal" method="post" id="shopForm" v-on:submit.prevent="saveShop">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3>
                            <span class="glyphicon glyphicon-leaf"></span>
                            Update Shop
                            <router-link to="/shop/form" title="Create a new shop">
                                <button type="button" class="btn btn-default pull-right">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </button>
                            </router-link>
                            <router-link to="/shop" title="Back to the list">
                                <button type="button" class="btn btn-link pull-right">
                                    List
                                </button>
                            </router-link>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <div v-bind:style="'display:'+status.display" class="panel-group">
                            <div v-bind:class="'panel panel-'+status.bootstrapPanelColor">
                                <div class="panel-heading">{{ status.status }}
                                    <div class="panel panel-body">{{ status.message }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div v-bind:style="'display:'+form.display">
                        <div class="form-group">
                            <label class="col-sm-2">code *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="shop.code" placeholder="Enter Shop code" disabled  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">name</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="shop.name" placeholder="Enter Shop name"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">address1</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="shop.address1" placeholder="Enter Shop address1"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">address2</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="shop.address2" placeholder="Enter Shop address2"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">zipCode</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="shop.zipCode" placeholder="Enter Shop zipCode"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">city</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="shop.city" placeholder="Enter Shop city"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">countryCode *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="shop.countryCode" placeholder="Enter Shop countryCode"  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">phone</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="shop.phone" placeholder="Enter Shop phone"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">email</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="shop.email" placeholder="Enter Shop email"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">executive</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="shop.executive" placeholder="Enter Shop executive"  >
                            </div>
                        </div>
                        </div>
                    </div>
                    <div class="panel-footer" v-bind:style="'display:'+form.display">
                        <a @click="showModal = true; editShop(shop)" title="Delete this shop">
                            <button type="button" class="btn btn-danger pull-right"><span class="glyphicon glyphicon-trash"></span> Delete
                            </button>
                        </a>
                        <modal v-if="showModal" @close="showModal = false">
                        	<div slot="footer">
                                <div slot="footer">
                                    <button type="button" class="btn btn-success pull-right" title="Delete this shop" v-on:click.prevent="showModal = false; deleteShop(modalData)">Yes</button>
                                </div>
                        	</div>
                        </modal>
                        <div title="Submit changes">
                            <button type="submit" formaction="/shop/update" class="btn btn-success"><span class="glyphicon glyphicon-floppy-disk"></span> Save
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <script type="text/x-template" id="modal-template">
                <transition name="modal">
                    <div class="modal-mask">
                        <div class="modal-wrapper">
                            <div class="container modal-container">
                                <div class="panel-group">
                                    <div class="panel panel-info">
                                        <div class="panel-heading">
                                            <h3>Warning</h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete this shop ?
                                </div>
                                <div class="modal-footer">
                                    <div class="btn-toolbar">
                                        <button type="button" class="btn btn-danger pull-right"
                                                title="Cancel and close this panel" @click="$emit('close')">No
                                        </button>
                                        <slot name="footer">
                                        </slot>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </transition>
            </script>
        </form>
    </div>
    </div>
</template>

<script>
    import Vue from 'vue'
    import common from '../../common.js'
    import config from '../../../config/config.js'
    import modal from '../modal'

    export default {
        name: 'ShopUpdate',
        data() {
            let id = this.$route.params.id;
            let router = this.$router;
			let http = this.$http;
            return new Vue({
                el: '#shopUpdate',
                data: {
                    shop: {},
                    modalData: {},
                    showModal: false,
                    status: {
                        status: null,
                        message: null,
                        display: "none",
                        bootstrapPanelColor: null,
                    },
                    form: {
                        display: "block"
                    }
                },
                created: function () {
                    this.fetchData();
                },
                methods: {
                    saveShop: function (event) {
                        let shop = {
                            'code': this.shop.code,
                    		'name': this.shop.name,
                    		'address1': this.shop.address1,
                    		'address2': this.shop.address2,
                    		'zipCode': this.shop.zipCode,
                    		'city': this.shop.city,
                    		'countryCode': this.shop.countryCode,
                    		'phone': this.shop.phone,
                    		'email': this.shop.email,
                    		'executive': this.shop.executive,
                    		
                        };
						http.put(config.urlApi+'/shop', shop).then(response => {
                            common.apiConnect(this, response);
                            this.fetchData();
                        }, response => {
                            common.apiUnreachable(this);
                        });
                        this.status.display = "block";
                    },
                    deleteShop: function (modalData) {
						{
                            http.delete(config.urlApi+'/shop/'+modalData.code).then(response => {
                                common.apiConnect(this, response);
                                if (response.status === 204) {
                                    this.form.display = "none";
                                    setTimeout(function () {
                                        router.push('/shop');
                                    }, 3000);
                                }
                            }, response => {
                                common.apiUnreachable(this);
                            });
                            this.status.display = "block";
                        }
                    },
                    editShop (shop) {
                        this.modalData = shop;
                    },
                    fetchData: function () {
                        {
                            http.get(config.urlApi+'/shop/'+id).then(response => {
                                if(response.body) {
                                    this.shop = response.body;
                                }
                            }, response => {
                            common.apiUnreachable(this, response);
                                this.status.display = "block";
                            });
                        }
                    }
                }
            });
        }
    }
</script>