/*
 * Created on 2018-01-15 ( Time 10:40:28 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
<template>
    <div class="container">
    <div class="container">
        <form class="form-horizontal" method="post" id="reviewForm" v-on:submit.prevent="saveReview">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3>
                            <span class="glyphicon glyphicon-leaf"></span>
                            Update Review
                            <router-link to="/review/form" title="Create a new review">
                                <button type="button" class="btn btn-default pull-right">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </button>
                            </router-link>
                            <router-link to="/review" title="Back to the list">
                                <button type="button" class="btn btn-link pull-right">
                                    List
                                </button>
                            </router-link>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <div v-bind:style="'display:'+status.display" class="panel-group">
                            <div v-bind:class="'panel panel-'+status.bootstrapPanelColor">
                                <div class="panel-heading">{{ status.status }}
                                    <div class="panel panel-body">{{ status.message }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div v-bind:style="'display:'+form.display">
                        <div class="form-group">
                            <label class="col-sm-2">customerCode *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="review.customerCode" placeholder="Enter Review customerCode" disabled  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">bookId *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="review.bookId" placeholder="Enter Review bookId" disabled  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">reviewText</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="review.reviewText" placeholder="Enter Review reviewText"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">reviewNote</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="review.reviewNote" placeholder="Enter Review reviewNote"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">creation</label>
                            <div class="col-sm-8">
                            	<input type="date" class="form-control"
                           				v-model="review.creation" placeholder="Enter Review creation"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">lastUpdate</label>
                            <div class="col-sm-8">
                            	<input type="date" class="form-control"
                           				v-model="review.lastUpdate" placeholder="Enter Review lastUpdate"  >
                            </div>
                        </div>
                        </div>
                    </div>
                    <div class="panel-footer" v-bind:style="'display:'+form.display">
                        <a @click="showModal = true; editReview(review)" title="Delete this review">
                            <button type="button" class="btn btn-danger pull-right"><span class="glyphicon glyphicon-trash"></span> Delete
                            </button>
                        </a>
                        <modal v-if="showModal" @close="showModal = false">
                        	<div slot="footer">
                                <div slot="footer">
                                    <button type="button" class="btn btn-success pull-right" title="Delete this review" v-on:click.prevent="showModal = false; deleteReview(modalData)">Yes</button>
                                </div>
                        	</div>
                        </modal>
                        <div title="Submit changes">
                            <button type="submit" formaction="/review/update" class="btn btn-success"><span class="glyphicon glyphicon-floppy-disk"></span> Save
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <script type="text/x-template" id="modal-template">
                <transition name="modal">
                    <div class="modal-mask">
                        <div class="modal-wrapper">
                            <div class="container modal-container">
                                <div class="panel-group">
                                    <div class="panel panel-info">
                                        <div class="panel-heading">
                                            <h3>Warning</h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete this review ?
                                </div>
                                <div class="modal-footer">
                                    <div class="btn-toolbar">
                                        <button type="button" class="btn btn-danger pull-right"
                                                title="Cancel and close this panel" @click="$emit('close')">No
                                        </button>
                                        <slot name="footer">
                                        </slot>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </transition>
            </script>
        </form>
    </div>
    </div>
</template>

<script>
    import Vue from 'vue'
    import common from '../../common.js'
    import config from '../../../config/config.js'
    import modal from '../modal'

    export default {
        name: 'ReviewUpdate',
        data() {
            let id = this.$route.params.id;
            let router = this.$router;
			let http = this.$http;
            return new Vue({
                el: '#reviewUpdate',
                data: {
                    review: {},
                    modalData: {},
                    showModal: false,
                    status: {
                        status: null,
                        message: null,
                        display: "none",
                        bootstrapPanelColor: null,
                    },
                    form: {
                        display: "block"
                    }
                },
                created: function () {
                    this.fetchData();
                },
                methods: {
                    saveReview: function (event) {
                        let review = {
                            'customerCode': this.review.customerCode,
                    		'bookId': this.review.bookId,
                    		'reviewText': this.review.reviewText,
                    		'reviewNote': this.review.reviewNote,
                    		'creation': this.review.creation,
                    		'lastUpdate': this.review.lastUpdate,
                    		
                        };
						http.put(config.urlApi+'/review', review).then(response => {
                            common.apiConnect(this, response);
                            this.fetchData();
                        }, response => {
                            common.apiUnreachable(this);
                        });
                        this.status.display = "block";
                    },
                    deleteReview: function (modalData) {
						{
                            http.delete(config.urlApi+'/review/'+modalData.customerCode+'/'+modalData.bookId).then(response => {
                                common.apiConnect(this, response);
                                if (response.status === 204) {
                                    this.form.display = "none";
                                    setTimeout(function () {
                                        router.push('/review');
                                    }, 3000);
                                }
                            }, response => {
                                common.apiUnreachable(this);
                            });
                            this.status.display = "block";
                        }
                    },
                    editReview (review) {
                        this.modalData = review;
                    },
                    fetchData: function () {
                        {
                            http.get(config.urlApi+'/review/'+id).then(response => {
                                if(response.body) {
                                    this.review = response.body;
                                }
                            }, response => {
                            common.apiUnreachable(this, response);
                                this.status.display = "block";
                            });
                        }
                    }
                }
            });
        }
    }
</script>