/*
 * Created on 2018-01-15 ( Time 10:40:28 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
<template>
    <div class="container">
    <div class="container">
        <form class="form-horizontal" method="post" id="publisherForm" v-on:submit.prevent="savePublisher">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3>
                            <span class="glyphicon glyphicon-leaf"></span>
                            Update Publisher
                            <router-link to="/publisher/form" title="Create a new publisher">
                                <button type="button" class="btn btn-default pull-right">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </button>
                            </router-link>
                            <router-link to="/publisher" title="Back to the list">
                                <button type="button" class="btn btn-link pull-right">
                                    List
                                </button>
                            </router-link>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <div v-bind:style="'display:'+status.display" class="panel-group">
                            <div v-bind:class="'panel panel-'+status.bootstrapPanelColor">
                                <div class="panel-heading">{{ status.status }}
                                    <div class="panel panel-body">{{ status.message }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div v-bind:style="'display:'+form.display">
                        <div class="form-group">
                            <label class="col-sm-2">code *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="publisher.code" placeholder="Enter Publisher code" disabled  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">countryCode *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="publisher.countryCode" placeholder="Enter Publisher countryCode"  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">name</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="publisher.name" placeholder="Enter Publisher name"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">email</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="publisher.email" placeholder="Enter Publisher email"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">contact</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="publisher.contact" placeholder="Enter Publisher contact"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">city</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="publisher.city" placeholder="Enter Publisher city"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">zipCode</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="publisher.zipCode" placeholder="Enter Publisher zipCode"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">phone</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="publisher.phone" placeholder="Enter Publisher phone"  >
                            </div>
                        </div>
                        </div>
                    </div>
                    <div class="panel-footer" v-bind:style="'display:'+form.display">
                        <a @click="showModal = true; editPublisher(publisher)" title="Delete this publisher">
                            <button type="button" class="btn btn-danger pull-right"><span class="glyphicon glyphicon-trash"></span> Delete
                            </button>
                        </a>
                        <modal v-if="showModal" @close="showModal = false">
                        	<div slot="footer">
                                <div slot="footer">
                                    <button type="button" class="btn btn-success pull-right" title="Delete this publisher" v-on:click.prevent="showModal = false; deletePublisher(modalData)">Yes</button>
                                </div>
                        	</div>
                        </modal>
                        <div title="Submit changes">
                            <button type="submit" formaction="/publisher/update" class="btn btn-success"><span class="glyphicon glyphicon-floppy-disk"></span> Save
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <script type="text/x-template" id="modal-template">
                <transition name="modal">
                    <div class="modal-mask">
                        <div class="modal-wrapper">
                            <div class="container modal-container">
                                <div class="panel-group">
                                    <div class="panel panel-info">
                                        <div class="panel-heading">
                                            <h3>Warning</h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete this publisher ?
                                </div>
                                <div class="modal-footer">
                                    <div class="btn-toolbar">
                                        <button type="button" class="btn btn-danger pull-right"
                                                title="Cancel and close this panel" @click="$emit('close')">No
                                        </button>
                                        <slot name="footer">
                                        </slot>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </transition>
            </script>
        </form>
    </div>
    </div>
</template>

<script>
    import Vue from 'vue'
    import common from '../../common.js'
    import config from '../../../config/config.js'
    import modal from '../modal'

    export default {
        name: 'PublisherUpdate',
        data() {
            let id = this.$route.params.id;
            let router = this.$router;
			let http = this.$http;
            return new Vue({
                el: '#publisherUpdate',
                data: {
                    publisher: {},
                    modalData: {},
                    showModal: false,
                    status: {
                        status: null,
                        message: null,
                        display: "none",
                        bootstrapPanelColor: null,
                    },
                    form: {
                        display: "block"
                    }
                },
                created: function () {
                    this.fetchData();
                },
                methods: {
                    savePublisher: function (event) {
                        let publisher = {
                            'code': this.publisher.code,
                    		'countryCode': this.publisher.countryCode,
                    		'name': this.publisher.name,
                    		'email': this.publisher.email,
                    		'contact': this.publisher.contact,
                    		'city': this.publisher.city,
                    		'zipCode': this.publisher.zipCode,
                    		'phone': this.publisher.phone,
                    		
                        };
						http.put(config.urlApi+'/publisher', publisher).then(response => {
                            common.apiConnect(this, response);
                            this.fetchData();
                        }, response => {
                            common.apiUnreachable(this);
                        });
                        this.status.display = "block";
                    },
                    deletePublisher: function (modalData) {
						{
                            http.delete(config.urlApi+'/publisher/'+modalData.code).then(response => {
                                common.apiConnect(this, response);
                                if (response.status === 204) {
                                    this.form.display = "none";
                                    setTimeout(function () {
                                        router.push('/publisher');
                                    }, 3000);
                                }
                            }, response => {
                                common.apiUnreachable(this);
                            });
                            this.status.display = "block";
                        }
                    },
                    editPublisher (publisher) {
                        this.modalData = publisher;
                    },
                    fetchData: function () {
                        {
                            http.get(config.urlApi+'/publisher/'+id).then(response => {
                                if(response.body) {
                                    this.publisher = response.body;
                                }
                            }, response => {
                            common.apiUnreachable(this, response);
                                this.status.display = "block";
                            });
                        }
                    }
                }
            });
        }
    }
</script>