/*
 * Created on 2018-01-15 ( Time 10:47:00 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
<template>
    <div class="container">
    <div class="container">
        <form class="form-horizontal" method="post" id="customerForm" v-on:submit.prevent="saveCustomer">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3>
                            <span class="glyphicon glyphicon-leaf"></span>
                            Update Customer
                            <router-link to="/customer/form" title="Create a new customer">
                                <button type="button" class="btn btn-default pull-right">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </button>
                            </router-link>
                            <router-link to="/customer" title="Back to the list">
                                <button type="button" class="btn btn-link pull-right">
                                    List
                                </button>
                            </router-link>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <div v-bind:style="'display:'+status.display" class="panel-group">
                            <div v-bind:class="'panel panel-'+status.bootstrapPanelColor">
                                <div class="panel-heading">{{ status.status }}
                                    <div class="panel panel-body">{{ status.message }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div v-bind:style="'display:'+form.display">
                        <div class="form-group">
                            <label class="col-sm-2">code *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="customer.code" placeholder="Enter Customer code" disabled  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">countryCode *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="customer.countryCode" placeholder="Enter Customer countryCode"  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">firstName</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="customer.firstName" placeholder="Enter Customer firstName"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">lastName</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="customer.lastName" placeholder="Enter Customer lastName"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">login *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="customer.login" placeholder="Enter Customer login"  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">password</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="customer.password" placeholder="Enter Customer password"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">age</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="customer.age" placeholder="Enter Customer age"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">city</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="customer.city" placeholder="Enter Customer city"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">zipCode</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="customer.zipCode" placeholder="Enter Customer zipCode"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">phone</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="customer.phone" placeholder="Enter Customer phone"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">reviewer</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="customer.reviewer" placeholder="Enter Customer reviewer"  >
                            </div>
                        </div>
                        </div>
                    </div>
                    <div class="panel-footer" v-bind:style="'display:'+form.display">
                        <a @click="showModal = true; editCustomer(customer)" title="Delete this customer">
                            <button type="button" class="btn btn-danger pull-right"><span class="glyphicon glyphicon-trash"></span> Delete
                            </button>
                        </a>
                        <modal v-if="showModal" @close="showModal = false">
                        	<div slot="footer">
                                <div slot="footer">
                                    <button type="button" class="btn btn-success pull-right" title="Delete this customer" v-on:click.prevent="showModal = false; deleteCustomer(modalData)">Yes</button>
                                </div>
                        	</div>
                        </modal>
                        <div title="Submit changes">
                            <button type="submit" formaction="/customer/update" class="btn btn-success"><span class="glyphicon glyphicon-floppy-disk"></span> Save
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <script type="text/x-template" id="modal-template">
                <transition name="modal">
                    <div class="modal-mask">
                        <div class="modal-wrapper">
                            <div class="container modal-container">
                                <div class="panel-group">
                                    <div class="panel panel-info">
                                        <div class="panel-heading">
                                            <h3>Warning</h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete this customer ?
                                </div>
                                <div class="modal-footer">
                                    <div class="btn-toolbar">
                                        <button type="button" class="btn btn-danger pull-right"
                                                title="Cancel and close this panel" @click="$emit('close')">No
                                        </button>
                                        <slot name="footer">
                                        </slot>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </transition>
            </script>
        </form>
    </div>
    </div>
</template>

<script>
    import Vue from 'vue'
    import common from '../../common.js'
    import config from '../../../config/config.js'
    import modal from '../modal'

    export default {
        name: 'CustomerUpdate',
        data() {
            let id = this.$route.params.id;
            let router = this.$router;
			let http = this.$http;
            return new Vue({
                el: '#customerUpdate',
                data: {
                    customer: {},
                    modalData: {},
                    showModal: false,
                    status: {
                        status: null,
                        message: null,
                        display: "none",
                        bootstrapPanelColor: null,
                    },
                    form: {
                        display: "block"
                    }
                },
                created: function () {
                    this.fetchData();
                },
                methods: {
                    saveCustomer: function (event) {
                        let customer = {
                            'code': this.customer.code,
                    		'countryCode': this.customer.countryCode,
                    		'firstName': this.customer.firstName,
                    		'lastName': this.customer.lastName,
                    		'login': this.customer.login,
                    		'password': this.customer.password,
                    		'age': this.customer.age,
                    		'city': this.customer.city,
                    		'zipCode': this.customer.zipCode,
                    		'phone': this.customer.phone,
                    		'reviewer': this.customer.reviewer,
                    		
                        };
						http.put(config.urlApi+'/customer', customer).then(response => {
                            common.apiConnect(this, response);
                            this.fetchData();
                        }, response => {
                            common.apiUnreachable(this);
                        });
                        this.status.display = "block";
                    },
                    deleteCustomer: function (modalData) {
						{
                            http.delete(config.urlApi+'/customer/'+modalData.code).then(response => {
                                common.apiConnect(this, response);
                                if (response.status === 204) {
                                    this.form.display = "none";
                                    setTimeout(function () {
                                        router.push('/customer');
                                    }, 3000);
                                }
                            }, response => {
                                common.apiUnreachable(this);
                            });
                            this.status.display = "block";
                        }
                    },
                    editCustomer (customer) {
                        this.modalData = customer;
                    },
                    fetchData: function () {
                        {
                            http.get(config.urlApi+'/customer/'+id).then(response => {
                                if(response.body) {
                                    this.customer = response.body;
                                }
                            }, response => {
                            common.apiUnreachable(this, response);
                                this.status.display = "block";
                            });
                        }
                    }
                }
            });
        }
    }
</script>