/*
 * Created on 2017-10-03 ( Time 10:59:49 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 * Front configuration
 */

export default ({
    urlApi: 'http://localhost:3000/api/v1',
    entities: [
        'author',
        'badge',
        'book',
        'bookOrder',
        'bookOrderItem',
        'country',
        'customer',
        'employee',
        'employeeGroup',
        'publisher',
        'review',
        'shop',
        'synopsis',
        'workgroup',
    ]
});