/*
 * Created on 2018-01-15 ( Time 10:47:00 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
<template>
    <div class="container">
    <div class="container">
        <form class="form-horizontal" method="post" id="employeeForm" v-on:submit.prevent="saveEmployee">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3>
                            <span class="glyphicon glyphicon-leaf"></span>
                            Update Employee
                            <router-link to="/employee/form" title="Create a new employee">
                                <button type="button" class="btn btn-default pull-right">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </button>
                            </router-link>
                            <router-link to="/employee" title="Back to the list">
                                <button type="button" class="btn btn-link pull-right">
                                    List
                                </button>
                            </router-link>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <div v-bind:style="'display:'+status.display" class="panel-group">
                            <div v-bind:class="'panel panel-'+status.bootstrapPanelColor">
                                <div class="panel-heading">{{ status.status }}
                                    <div class="panel panel-body">{{ status.message }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div v-bind:style="'display:'+form.display">
                        <div class="form-group">
                            <label class="col-sm-2">code *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="employee.code" placeholder="Enter Employee code" disabled  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">shopCode *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="employee.shopCode" placeholder="Enter Employee shopCode"  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">firstName</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="employee.firstName" placeholder="Enter Employee firstName"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">lastName *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="employee.lastName" placeholder="Enter Employee lastName"  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">manager</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="employee.manager" placeholder="Enter Employee manager"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">badgeNumber</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="employee.badgeNumber" placeholder="Enter Employee badgeNumber"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">email</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="employee.email" placeholder="Enter Employee email"  >
                            </div>
                        </div>
                        </div>
                    </div>
                    <div class="panel-footer" v-bind:style="'display:'+form.display">
                        <a @click="showModal = true; editEmployee(employee)" title="Delete this employee">
                            <button type="button" class="btn btn-danger pull-right"><span class="glyphicon glyphicon-trash"></span> Delete
                            </button>
                        </a>
                        <modal v-if="showModal" @close="showModal = false">
                        	<div slot="footer">
                                <div slot="footer">
                                    <button type="button" class="btn btn-success pull-right" title="Delete this employee" v-on:click.prevent="showModal = false; deleteEmployee(modalData)">Yes</button>
                                </div>
                        	</div>
                        </modal>
                        <div title="Submit changes">
                            <button type="submit" formaction="/employee/update" class="btn btn-success"><span class="glyphicon glyphicon-floppy-disk"></span> Save
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <script type="text/x-template" id="modal-template">
                <transition name="modal">
                    <div class="modal-mask">
                        <div class="modal-wrapper">
                            <div class="container modal-container">
                                <div class="panel-group">
                                    <div class="panel panel-info">
                                        <div class="panel-heading">
                                            <h3>Warning</h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete this employee ?
                                </div>
                                <div class="modal-footer">
                                    <div class="btn-toolbar">
                                        <button type="button" class="btn btn-danger pull-right"
                                                title="Cancel and close this panel" @click="$emit('close')">No
                                        </button>
                                        <slot name="footer">
                                        </slot>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </transition>
            </script>
        </form>
    </div>
    </div>
</template>

<script>
    import Vue from 'vue'
    import common from '../../common.js'
    import config from '../../../config/config.js'
    import modal from '../modal'

    export default {
        name: 'EmployeeUpdate',
        data() {
            let id = this.$route.params.id;
            let router = this.$router;
			let http = this.$http;
            return new Vue({
                el: '#employeeUpdate',
                data: {
                    employee: {},
                    modalData: {},
                    showModal: false,
                    status: {
                        status: null,
                        message: null,
                        display: "none",
                        bootstrapPanelColor: null,
                    },
                    form: {
                        display: "block"
                    }
                },
                created: function () {
                    this.fetchData();
                },
                methods: {
                    saveEmployee: function (event) {
                        let employee = {
                            'code': this.employee.code,
                    		'shopCode': this.employee.shopCode,
                    		'firstName': this.employee.firstName,
                    		'lastName': this.employee.lastName,
                    		'manager': this.employee.manager,
                    		'badgeNumber': this.employee.badgeNumber,
                    		'email': this.employee.email,
                    		
                        };
						http.put(config.urlApi+'/employee', employee).then(response => {
                            common.apiConnect(this, response);
                            this.fetchData();
                        }, response => {
                            common.apiUnreachable(this);
                        });
                        this.status.display = "block";
                    },
                    deleteEmployee: function (modalData) {
						{
                            http.delete(config.urlApi+'/employee/'+modalData.code).then(response => {
                                common.apiConnect(this, response);
                                if (response.status === 204) {
                                    this.form.display = "none";
                                    setTimeout(function () {
                                        router.push('/employee');
                                    }, 3000);
                                }
                            }, response => {
                                common.apiUnreachable(this);
                            });
                            this.status.display = "block";
                        }
                    },
                    editEmployee (employee) {
                        this.modalData = employee;
                    },
                    fetchData: function () {
                        {
                            http.get(config.urlApi+'/employee/'+id).then(response => {
                                if(response.body) {
                                    this.employee = response.body;
                                }
                            }, response => {
                            common.apiUnreachable(this, response);
                                this.status.display = "block";
                            });
                        }
                    }
                }
            });
        }
    }
</script>