/*
 * Created on 2018-01-15 ( Time 10:40:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
<template>
    <div class="container">
    <div class="container">
        <form class="form-horizontal" method="post" id="bookOrderForm" v-on:submit.prevent="saveBookOrder">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3>
                            <span class="glyphicon glyphicon-leaf"></span>
                            Update BookOrder
                            <router-link to="/bookOrder/form" title="Create a new bookOrder">
                                <button type="button" class="btn btn-default pull-right">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </button>
                            </router-link>
                            <router-link to="/bookOrder" title="Back to the list">
                                <button type="button" class="btn btn-link pull-right">
                                    List
                                </button>
                            </router-link>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <div v-bind:style="'display:'+status.display" class="panel-group">
                            <div v-bind:class="'panel panel-'+status.bootstrapPanelColor">
                                <div class="panel-heading">{{ status.status }}
                                    <div class="panel panel-body">{{ status.message }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div v-bind:style="'display:'+form.display">
                        <div class="form-group">
                            <label class="col-sm-2">id *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="bookOrder.id" placeholder="Enter BookOrder id" disabled  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">shopCode *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="bookOrder.shopCode" placeholder="Enter BookOrder shopCode"  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">customerCode *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="bookOrder.customerCode" placeholder="Enter BookOrder customerCode"  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">employeeCode *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="bookOrder.employeeCode" placeholder="Enter BookOrder employeeCode"  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">date</label>
                            <div class="col-sm-8">
                            	<input type="date" class="form-control"
                           				v-model="bookOrder.date" placeholder="Enter BookOrder date"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">state</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="bookOrder.state" placeholder="Enter BookOrder state"  >
                            </div>
                        </div>
                        </div>
                    </div>
                    <div class="panel-footer" v-bind:style="'display:'+form.display">
                        <a @click="showModal = true; editBookOrder(bookOrder)" title="Delete this bookOrder">
                            <button type="button" class="btn btn-danger pull-right"><span class="glyphicon glyphicon-trash"></span> Delete
                            </button>
                        </a>
                        <modal v-if="showModal" @close="showModal = false">
                        	<div slot="footer">
                                <div slot="footer">
                                    <button type="button" class="btn btn-success pull-right" title="Delete this bookOrder" v-on:click.prevent="showModal = false; deleteBookOrder(modalData)">Yes</button>
                                </div>
                        	</div>
                        </modal>
                        <div title="Submit changes">
                            <button type="submit" formaction="/bookOrder/update" class="btn btn-success"><span class="glyphicon glyphicon-floppy-disk"></span> Save
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <script type="text/x-template" id="modal-template">
                <transition name="modal">
                    <div class="modal-mask">
                        <div class="modal-wrapper">
                            <div class="container modal-container">
                                <div class="panel-group">
                                    <div class="panel panel-info">
                                        <div class="panel-heading">
                                            <h3>Warning</h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete this bookOrder ?
                                </div>
                                <div class="modal-footer">
                                    <div class="btn-toolbar">
                                        <button type="button" class="btn btn-danger pull-right"
                                                title="Cancel and close this panel" @click="$emit('close')">No
                                        </button>
                                        <slot name="footer">
                                        </slot>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </transition>
            </script>
        </form>
    </div>
    </div>
</template>

<script>
    import Vue from 'vue'
    import common from '../../common.js'
    import config from '../../../config/config.js'
    import modal from '../modal'

    export default {
        name: 'BookOrderUpdate',
        data() {
            let id = this.$route.params.id;
            let router = this.$router;
			let http = this.$http;
            return new Vue({
                el: '#bookOrderUpdate',
                data: {
                    bookOrder: {},
                    modalData: {},
                    showModal: false,
                    status: {
                        status: null,
                        message: null,
                        display: "none",
                        bootstrapPanelColor: null,
                    },
                    form: {
                        display: "block"
                    }
                },
                created: function () {
                    this.fetchData();
                },
                methods: {
                    saveBookOrder: function (event) {
                        let bookOrder = {
                            'id': this.bookOrder.id,
                    		'shopCode': this.bookOrder.shopCode,
                    		'customerCode': this.bookOrder.customerCode,
                    		'employeeCode': this.bookOrder.employeeCode,
                    		'date': this.bookOrder.date,
                    		'state': this.bookOrder.state,
                    		
                        };
						http.put(config.urlApi+'/bookOrder', bookOrder).then(response => {
                            common.apiConnect(this, response);
                            this.fetchData();
                        }, response => {
                            common.apiUnreachable(this);
                        });
                        this.status.display = "block";
                    },
                    deleteBookOrder: function (modalData) {
						{
                            http.delete(config.urlApi+'/bookOrder/'+modalData.id).then(response => {
                                common.apiConnect(this, response);
                                if (response.status === 204) {
                                    this.form.display = "none";
                                    setTimeout(function () {
                                        router.push('/bookOrder');
                                    }, 3000);
                                }
                            }, response => {
                                common.apiUnreachable(this);
                            });
                            this.status.display = "block";
                        }
                    },
                    editBookOrder (bookOrder) {
                        this.modalData = bookOrder;
                    },
                    fetchData: function () {
                        {
                            http.get(config.urlApi+'/bookOrder/'+id).then(response => {
                                if(response.body) {
                                    this.bookOrder = response.body;
                                }
                            }, response => {
                            common.apiUnreachable(this, response);
                                this.status.display = "block";
                            });
                        }
                    }
                }
            });
        }
    }
</script>