/*
 * Created on 2018-01-15 ( Time 10:40:29 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
import Vue from 'vue'
import Router from 'vue-router'
import Home from '@/components/home'
import AuthorIndex from '@/components/author/authorIndex'
import AuthorUpdate from '@/components/author/authorUpdate'
import AuthorCreate from '@/components/author/authorCreate'
import BadgeIndex from '@/components/badge/badgeIndex'
import BadgeUpdate from '@/components/badge/badgeUpdate'
import BadgeCreate from '@/components/badge/badgeCreate'
import BookIndex from '@/components/book/bookIndex'
import BookUpdate from '@/components/book/bookUpdate'
import BookCreate from '@/components/book/bookCreate'
import BookOrderIndex from '@/components/bookOrder/bookOrderIndex'
import BookOrderUpdate from '@/components/bookOrder/bookOrderUpdate'
import BookOrderCreate from '@/components/bookOrder/bookOrderCreate'
import BookOrderItemIndex from '@/components/bookOrderItem/bookOrderItemIndex'
import BookOrderItemUpdate from '@/components/bookOrderItem/bookOrderItemUpdate'
import BookOrderItemCreate from '@/components/bookOrderItem/bookOrderItemCreate'
import CountryIndex from '@/components/country/countryIndex'
import CountryUpdate from '@/components/country/countryUpdate'
import CountryCreate from '@/components/country/countryCreate'
import CustomerIndex from '@/components/customer/customerIndex'
import CustomerUpdate from '@/components/customer/customerUpdate'
import CustomerCreate from '@/components/customer/customerCreate'
import EmployeeIndex from '@/components/employee/employeeIndex'
import EmployeeUpdate from '@/components/employee/employeeUpdate'
import EmployeeCreate from '@/components/employee/employeeCreate'
import EmployeeGroupIndex from '@/components/employeeGroup/employeeGroupIndex'
import EmployeeGroupUpdate from '@/components/employeeGroup/employeeGroupUpdate'
import EmployeeGroupCreate from '@/components/employeeGroup/employeeGroupCreate'
import PublisherIndex from '@/components/publisher/publisherIndex'
import PublisherUpdate from '@/components/publisher/publisherUpdate'
import PublisherCreate from '@/components/publisher/publisherCreate'
import ReviewIndex from '@/components/review/reviewIndex'
import ReviewUpdate from '@/components/review/reviewUpdate'
import ReviewCreate from '@/components/review/reviewCreate'
import ShopIndex from '@/components/shop/shopIndex'
import ShopUpdate from '@/components/shop/shopUpdate'
import ShopCreate from '@/components/shop/shopCreate'
import SynopsisIndex from '@/components/synopsis/synopsisIndex'
import SynopsisUpdate from '@/components/synopsis/synopsisUpdate'
import SynopsisCreate from '@/components/synopsis/synopsisCreate'
import WorkgroupIndex from '@/components/workgroup/workgroupIndex'
import WorkgroupUpdate from '@/components/workgroup/workgroupUpdate'
import WorkgroupCreate from '@/components/workgroup/workgroupCreate'

Vue.use(Router);

export default new Router({
    routes: [
        { path: '/', name: 'Home', component: Home },
        { path: '/author', name: 'authorIndex', component: AuthorIndex },
        { path: '/author/form/:id', name: 'authorUpdate', component: AuthorUpdate },
        { path: '/author/form/', name: 'authorCreate', component: AuthorCreate },
        { path: '/badge', name: 'badgeIndex', component: BadgeIndex },
        { path: '/badge/form/:badgeNumber', name: 'badgeUpdate', component: BadgeUpdate },
        { path: '/badge/form/', name: 'badgeCreate', component: BadgeCreate },
        { path: '/book', name: 'bookIndex', component: BookIndex },
        { path: '/book/form/:id', name: 'bookUpdate', component: BookUpdate },
        { path: '/book/form/', name: 'bookCreate', component: BookCreate },
        { path: '/bookOrder', name: 'bookOrderIndex', component: BookOrderIndex },
        { path: '/bookOrder/form/:id', name: 'bookOrderUpdate', component: BookOrderUpdate },
        { path: '/bookOrder/form/', name: 'bookOrderCreate', component: BookOrderCreate },
        { path: '/bookOrderItem', name: 'bookOrderItemIndex', component: BookOrderItemIndex },
        { path: '/bookOrderItem/form/:bookOrderId/:bookId', name: 'bookOrderItemUpdate', component: BookOrderItemUpdate },
        { path: '/bookOrderItem/form/', name: 'bookOrderItemCreate', component: BookOrderItemCreate },
        { path: '/country', name: 'countryIndex', component: CountryIndex },
        { path: '/country/form/:code', name: 'countryUpdate', component: CountryUpdate },
        { path: '/country/form/', name: 'countryCreate', component: CountryCreate },
        { path: '/customer', name: 'customerIndex', component: CustomerIndex },
        { path: '/customer/form/:code', name: 'customerUpdate', component: CustomerUpdate },
        { path: '/customer/form/', name: 'customerCreate', component: CustomerCreate },
        { path: '/employee', name: 'employeeIndex', component: EmployeeIndex },
        { path: '/employee/form/:code', name: 'employeeUpdate', component: EmployeeUpdate },
        { path: '/employee/form/', name: 'employeeCreate', component: EmployeeCreate },
        { path: '/employeeGroup', name: 'employeeGroupIndex', component: EmployeeGroupIndex },
        { path: '/employeeGroup/form/:employeeCode/:groupId', name: 'employeeGroupUpdate', component: EmployeeGroupUpdate },
        { path: '/employeeGroup/form/', name: 'employeeGroupCreate', component: EmployeeGroupCreate },
        { path: '/publisher', name: 'publisherIndex', component: PublisherIndex },
        { path: '/publisher/form/:code', name: 'publisherUpdate', component: PublisherUpdate },
        { path: '/publisher/form/', name: 'publisherCreate', component: PublisherCreate },
        { path: '/review', name: 'reviewIndex', component: ReviewIndex },
        { path: '/review/form/:customerCode/:bookId', name: 'reviewUpdate', component: ReviewUpdate },
        { path: '/review/form/', name: 'reviewCreate', component: ReviewCreate },
        { path: '/shop', name: 'shopIndex', component: ShopIndex },
        { path: '/shop/form/:code', name: 'shopUpdate', component: ShopUpdate },
        { path: '/shop/form/', name: 'shopCreate', component: ShopCreate },
        { path: '/synopsis', name: 'synopsisIndex', component: SynopsisIndex },
        { path: '/synopsis/form/:bookId', name: 'synopsisUpdate', component: SynopsisUpdate },
        { path: '/synopsis/form/', name: 'synopsisCreate', component: SynopsisCreate },
        { path: '/workgroup', name: 'workgroupIndex', component: WorkgroupIndex },
        { path: '/workgroup/form/:id', name: 'workgroupUpdate', component: WorkgroupUpdate },
        { path: '/workgroup/form/', name: 'workgroupCreate', component: WorkgroupCreate },
    ]
})