/*
 * Created on 2018-01-15 ( Time 10:40:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
<template>
    <div class="container">
    <div class="container">
        <form class="form-horizontal" method="post" id="bookForm" v-on:submit.prevent="saveBook">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3>
                            <span class="glyphicon glyphicon-leaf"></span>
                            Update Book
                            <router-link to="/book/form" title="Create a new book">
                                <button type="button" class="btn btn-default pull-right">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </button>
                            </router-link>
                            <router-link to="/book" title="Back to the list">
                                <button type="button" class="btn btn-link pull-right">
                                    List
                                </button>
                            </router-link>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <div v-bind:style="'display:'+status.display" class="panel-group">
                            <div v-bind:class="'panel panel-'+status.bootstrapPanelColor">
                                <div class="panel-heading">{{ status.status }}
                                    <div class="panel panel-body">{{ status.message }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div v-bind:style="'display:'+form.display">
                        <div class="form-group">
                            <label class="col-sm-2">id *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="book.id" placeholder="Enter Book id" disabled  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">publisherId *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="book.publisherId" placeholder="Enter Book publisherId"  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">authorId *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="book.authorId" placeholder="Enter Book authorId"  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">isbn *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="book.isbn" placeholder="Enter Book isbn"  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">title</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="book.title" placeholder="Enter Book title"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">price</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="book.price" placeholder="Enter Book price"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">quantity</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="book.quantity" placeholder="Enter Book quantity"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">discount</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="book.discount" placeholder="Enter Book discount"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">availability</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="book.availability" placeholder="Enter Book availability"  >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">bestSeller</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="book.bestSeller" placeholder="Enter Book bestSeller"  >
                            </div>
                        </div>
                        </div>
                    </div>
                    <div class="panel-footer" v-bind:style="'display:'+form.display">
                        <a @click="showModal = true; editBook(book)" title="Delete this book">
                            <button type="button" class="btn btn-danger pull-right"><span class="glyphicon glyphicon-trash"></span> Delete
                            </button>
                        </a>
                        <modal v-if="showModal" @close="showModal = false">
                        	<div slot="footer">
                                <div slot="footer">
                                    <button type="button" class="btn btn-success pull-right" title="Delete this book" v-on:click.prevent="showModal = false; deleteBook(modalData)">Yes</button>
                                </div>
                        	</div>
                        </modal>
                        <div title="Submit changes">
                            <button type="submit" formaction="/book/update" class="btn btn-success"><span class="glyphicon glyphicon-floppy-disk"></span> Save
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <script type="text/x-template" id="modal-template">
                <transition name="modal">
                    <div class="modal-mask">
                        <div class="modal-wrapper">
                            <div class="container modal-container">
                                <div class="panel-group">
                                    <div class="panel panel-info">
                                        <div class="panel-heading">
                                            <h3>Warning</h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete this book ?
                                </div>
                                <div class="modal-footer">
                                    <div class="btn-toolbar">
                                        <button type="button" class="btn btn-danger pull-right"
                                                title="Cancel and close this panel" @click="$emit('close')">No
                                        </button>
                                        <slot name="footer">
                                        </slot>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </transition>
            </script>
        </form>
    </div>
    </div>
</template>

<script>
    import Vue from 'vue'
    import common from '../../common.js'
    import config from '../../../config/config.js'
    import modal from '../modal'

    export default {
        name: 'BookUpdate',
        data() {
            let id = this.$route.params.id;
            let router = this.$router;
			let http = this.$http;
            return new Vue({
                el: '#bookUpdate',
                data: {
                    book: {},
                    modalData: {},
                    showModal: false,
                    status: {
                        status: null,
                        message: null,
                        display: "none",
                        bootstrapPanelColor: null,
                    },
                    form: {
                        display: "block"
                    }
                },
                created: function () {
                    this.fetchData();
                },
                methods: {
                    saveBook: function (event) {
                        let book = {
                            'id': this.book.id,
                    		'publisherId': this.book.publisherId,
                    		'authorId': this.book.authorId,
                    		'isbn': this.book.isbn,
                    		'title': this.book.title,
                    		'price': this.book.price,
                    		'quantity': this.book.quantity,
                    		'discount': this.book.discount,
                    		'availability': this.book.availability,
                    		'bestSeller': this.book.bestSeller,
                    		
                        };
						http.put(config.urlApi+'/book', book).then(response => {
                            common.apiConnect(this, response);
                            this.fetchData();
                        }, response => {
                            common.apiUnreachable(this);
                        });
                        this.status.display = "block";
                    },
                    deleteBook: function (modalData) {
						{
                            http.delete(config.urlApi+'/book/'+modalData.id).then(response => {
                                common.apiConnect(this, response);
                                if (response.status === 204) {
                                    this.form.display = "none";
                                    setTimeout(function () {
                                        router.push('/book');
                                    }, 3000);
                                }
                            }, response => {
                                common.apiUnreachable(this);
                            });
                            this.status.display = "block";
                        }
                    },
                    editBook (book) {
                        this.modalData = book;
                    },
                    fetchData: function () {
                        {
                            http.get(config.urlApi+'/book/'+id).then(response => {
                                if(response.body) {
                                    this.book = response.body;
                                }
                            }, response => {
                            common.apiUnreachable(this, response);
                                this.status.display = "block";
                            });
                        }
                    }
                }
            });
        }
    }
</script>