/*
 * Created on 2018-01-15 ( Time 10:47:00 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
<template>
    <div class="container">
    <div class="container">
        <form class="form-horizontal" method="post" id="bookOrderItemForm" v-on:submit.prevent="saveBookOrderItem">
            <div class="panel-group">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3>
                            <span class="glyphicon glyphicon-leaf"></span>
                            Update BookOrderItem
                            <router-link to="/bookOrderItem/form" title="Create a new bookOrderItem">
                                <button type="button" class="btn btn-default pull-right">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </button>
                            </router-link>
                            <router-link to="/bookOrderItem" title="Back to the list">
                                <button type="button" class="btn btn-link pull-right">
                                    List
                                </button>
                            </router-link>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <div v-bind:style="'display:'+status.display" class="panel-group">
                            <div v-bind:class="'panel panel-'+status.bootstrapPanelColor">
                                <div class="panel-heading">{{ status.status }}
                                    <div class="panel panel-body">{{ status.message }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div v-bind:style="'display:'+form.display">
                        <div class="form-group">
                            <label class="col-sm-2">bookOrderId *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="bookOrderItem.bookOrderId" placeholder="Enter BookOrderItem bookOrderId" disabled  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">bookId *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="bookOrderItem.bookId" placeholder="Enter BookOrderItem bookId" disabled  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">quantity *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="bookOrderItem.quantity" placeholder="Enter BookOrderItem quantity"  required >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">price *</label>
                            <div class="col-sm-8">
                            	<input type="text" class="form-control"
                           				v-model="bookOrderItem.price" placeholder="Enter BookOrderItem price"  required >
                            </div>
                        </div>
                        </div>
                    </div>
                    <div class="panel-footer" v-bind:style="'display:'+form.display">
                        <a @click="showModal = true; editBookOrderItem(bookOrderItem)" title="Delete this bookOrderItem">
                            <button type="button" class="btn btn-danger pull-right"><span class="glyphicon glyphicon-trash"></span> Delete
                            </button>
                        </a>
                        <modal v-if="showModal" @close="showModal = false">
                        	<div slot="footer">
                                <div slot="footer">
                                    <button type="button" class="btn btn-success pull-right" title="Delete this bookOrderItem" v-on:click.prevent="showModal = false; deleteBookOrderItem(modalData)">Yes</button>
                                </div>
                        	</div>
                        </modal>
                        <div title="Submit changes">
                            <button type="submit" formaction="/bookOrderItem/update" class="btn btn-success"><span class="glyphicon glyphicon-floppy-disk"></span> Save
                            </button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <script type="text/x-template" id="modal-template">
                <transition name="modal">
                    <div class="modal-mask">
                        <div class="modal-wrapper">
                            <div class="container modal-container">
                                <div class="panel-group">
                                    <div class="panel panel-info">
                                        <div class="panel-heading">
                                            <h3>Warning</h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-body">
                                    Are you sure you want to delete this bookOrderItem ?
                                </div>
                                <div class="modal-footer">
                                    <div class="btn-toolbar">
                                        <button type="button" class="btn btn-danger pull-right"
                                                title="Cancel and close this panel" @click="$emit('close')">No
                                        </button>
                                        <slot name="footer">
                                        </slot>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </transition>
            </script>
        </form>
    </div>
    </div>
</template>

<script>
    import Vue from 'vue'
    import common from '../../common.js'
    import config from '../../../config/config.js'
    import modal from '../modal'

    export default {
        name: 'BookOrderItemUpdate',
        data() {
            let id = this.$route.params.id;
            let router = this.$router;
			let http = this.$http;
            return new Vue({
                el: '#bookOrderItemUpdate',
                data: {
                    bookOrderItem: {},
                    modalData: {},
                    showModal: false,
                    status: {
                        status: null,
                        message: null,
                        display: "none",
                        bootstrapPanelColor: null,
                    },
                    form: {
                        display: "block"
                    }
                },
                created: function () {
                    this.fetchData();
                },
                methods: {
                    saveBookOrderItem: function (event) {
                        let bookOrderItem = {
                            'bookOrderId': this.bookOrderItem.bookOrderId,
                    		'bookId': this.bookOrderItem.bookId,
                    		'quantity': this.bookOrderItem.quantity,
                    		'price': this.bookOrderItem.price,
                    		
                        };
						http.put(config.urlApi+'/bookOrderItem', bookOrderItem).then(response => {
                            common.apiConnect(this, response);
                            this.fetchData();
                        }, response => {
                            common.apiUnreachable(this);
                        });
                        this.status.display = "block";
                    },
                    deleteBookOrderItem: function (modalData) {
						{
                            http.delete(config.urlApi+'/bookOrderItem/'+modalData.bookOrderId+'/'+modalData.bookId).then(response => {
                                common.apiConnect(this, response);
                                if (response.status === 204) {
                                    this.form.display = "none";
                                    setTimeout(function () {
                                        router.push('/bookOrderItem');
                                    }, 3000);
                                }
                            }, response => {
                                common.apiUnreachable(this);
                            });
                            this.status.display = "block";
                        }
                    },
                    editBookOrderItem (bookOrderItem) {
                        this.modalData = bookOrderItem;
                    },
                    fetchData: function () {
                        {
                            http.get(config.urlApi+'/bookOrderItem/'+id).then(response => {
                                if(response.body) {
                                    this.bookOrderItem = response.body;
                                }
                            }, response => {
                            common.apiUnreachable(this, response);
                                this.status.display = "block";
                            });
                        }
                    }
                }
            });
        }
    }
</script>